package com.music.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.music.bean.MusicInfo;
import com.music.bean.MusicList;

import com.music.bean.MusicInfoDao;
import com.music.bean.MusicListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicInfoDaoConfig;
    private final DaoConfig musicListDaoConfig;

    private final MusicInfoDao musicInfoDao;
    private final MusicListDao musicListDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicInfoDaoConfig = daoConfigMap.get(MusicInfoDao.class).clone();
        musicInfoDaoConfig.initIdentityScope(type);

        musicListDaoConfig = daoConfigMap.get(MusicListDao.class).clone();
        musicListDaoConfig.initIdentityScope(type);

        musicInfoDao = new MusicInfoDao(musicInfoDaoConfig, this);
        musicListDao = new MusicListDao(musicListDaoConfig, this);

        registerDao(MusicInfo.class, musicInfoDao);
        registerDao(MusicList.class, musicListDao);
    }
    
    public void clear() {
        musicInfoDaoConfig.clearIdentityScope();
        musicListDaoConfig.clearIdentityScope();
    }

    public MusicInfoDao getMusicInfoDao() {
        return musicInfoDao;
    }

    public MusicListDao getMusicListDao() {
        return musicListDao;
    }

}
